name: 1

on: 
  push:
    paths: 
      - '**'
    branches: 
      - main
  schedule:
    - cron: '* * * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装模块
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: start
      run: |
        python anoda2.py
